### ISSUE TITLE
Extended ports?

### ISSUE THREAD

**Issue by kf4mot** [erichVK5/WilkinsonPowerDividerFootprintGenerator#1]
Wonderful tool!
I'm wondering why I'm getting the extended tracks on the input/output ports though? Are they part of the 
calculated divider length or just an artifact? And if just an artifact any recommendation for removing them?
My variables are -r 500 -f 5660 -w 203 -l 50 -v 0.5 -p 380 -k
I'll attach an image.

![5660divider](https://user-images.githubusercontent.com/25356568/27668934-995bc5f2-5c49-11e7-9356-4fe9b0c44d4b.jpg)

**Comment by erichVK5** [comment]
The utility simply attached 3mm tracks at the input and output ports.

This is done near the end of the code, around lines 265 to 282, after the arc is generated, 
The terminals are not counted in the cumulative arc length.

The final three track definitions in the generated footprint are these terminals, i.e. in a kicad module generated by your settings:

DS 2.254 0.44 5.254 0.44 0.38 15
DS 2.254 -0.44 5.254 -0.44 0.38 15
DS -5.187 0 -2.187 0 0.38 15

these are the three 3 mm long arms. These can be edited, or deleted, in the generated footprint with a text editor. The DS format is in millimetres, and is as follows

DS x1 y1 x2 y2 thickness layer 

I have modified the code to allow a user specified terminal length using the option -t XXX for terminal length, XXX, specified in microns

i.e.

java WilkinsonPowerDividerFootprintGenerator -r 500 -f 5660 -w 203 -l 50 -v 0.5 -p 380 -k -t 500

will generate terminal arms 500 microns, i.e. 0.5mm, long on your divider.

if no -t XXX option is specified, then zero length, i.e. no terminals, are added.

Hope this helps!

Regards,

VK5HSE
